In [1]:
import numpy as np
import os

In [2]:
archivo = open('Pedido.txt','r')
lines = []
ingredientes = []
ingrediente = 'Ingrediente'

In [3]:
for line in archivo.readlines():
    lines.append(line)

In [4]:
lines.pop(0)

'9 1 1 1\n'

In [5]:
lines[5].split()

['4', 'cebolla', 'queso', 'garbanzo', 'aji']

In [11]:
NInicial = lines[0]
for j in range(len(lines)):
    ingrediente = lines[j]
    ListaI = ingrediente.split()
    for x in range(len(ListaI)):
        if x == 0:
            pass
        else:
            ingredienteActual = ListaI[x]
            ingredientes.append(ingredienteActual)

In [13]:
ingredientesF = []
for ing in ingredientes:
    if ing not in ingredientesF:
        ingredientesF.append(ing)

In [15]:
platos = lines
listaDeIngredientes = ingredientesF

In [16]:
cantidadDeIngredientes = len(listaDeIngredientes)
cantidadDePlatos = len(platos)

In [18]:
matriz = np.zeros((cantidadDeIngredientes,cantidadDePlatos))

In [20]:
def buscarPalabra(frase,palabra):
    if palabra in frase:
        return True
    return False

In [21]:
def reconocerIngredientes(plato, numeroPlato, matriz):
    i = 0
    for ing in listaDeIngredientes:
        cont = buscarPalabra(plato,ing)
        if cont:
            matriz[i][int(numeroPlato)]=1
        i = i + 1
    return matriz

In [22]:
num = 0
for i in platos:
    matriz =reconocerIngredientes(i,num,matriz)
    num = num + 1
print(matriz)

[[1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 1. 1. 1. 1.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 0. 0. 1. 1. 1. 1.]]


In [23]:
archivo.close()

In [59]:
archivo = open('myFile2.csv','r')

In [60]:
var = archivo.read()

In [69]:
lista = var.split()

In [70]:
lista.pop(0)

',,,,'

In [75]:
lista[0].split(',')

['415', '797.71', '592.17', '953', '35']

In [76]:
nuevaLista = []
for i in range(len(lista)):
    listaSplit = lista[i].split(',')
    listaFloat = []
    for j in range(len(listaSplit)):
        elemento = listaSplit[j]
        listaFloat.append(float(elemento))
    nuevaLista.append(listaFloat)
        

In [78]:
mayor = 0
for i in range(len(nuevaLista)):
    for j in range(len(nuevaLista[i])):
        if nuevaLista[i][j] > mayor:
            mayor = nuevaLista[i][j]
print(mayor)

1000.0


In [79]:
menor = 1000000
for i in range(len(nuevaLista)):
    for j in range(len(nuevaLista[i])):
        if nuevaLista[i][j] < menor:
            menor = nuevaLista[i][j]
print(menor)

1.17


In [81]:
suma = 0
numeroElementos = len(nuevaLista)*len(nuevaLista[0])
for i in range(len(nuevaLista)):
    for j in range(len(nuevaLista[i])):
        suma = suma + nuevaLista[i][j]
        
promedio = suma/numeroElementos
        
print(promedio)

506.61703399999953
